# Generated by Django 4.1 on 2022-10-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('fono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('estado_civil', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
